agentType: prometheus
type: exporter

name: nginx_collector_plugin
version: 1.0.0

category: Web 框架
params:
    - nginx_host
    - nginx_port
    - nginx_status_uri
    - exporter_host
    - exporter_port
    - exporter_uri
